export const LIST = {
  activity: { folderName: 'Identification' },
  identificationDetails: { folderName: 'Identification' },
  resume: { folderName: 'Identification' },
  consolidatedBalanceSheetAndIncomeStatement: { folderName: 'Financial Data' },
  consolidatedCashFlows: { folderName: 'Financial Data' },
  consolidatedEquityChanges: { folderName: 'Financial Data' },
  consolidatedFinancialAccounts: { folderName: 'Financial Data' },
  consolidatedFinancialConnections: { folderName: 'Financial Data' },
  consolidatedFinancialRatios: { folderName: 'Financial Data' },
  notesConsolidatedAccounts: { folderName: 'Financial Data' },
  notesOrdinaryAccounts: { folderName: 'Financial Data' },
  ordinaryBalanceSheetAndIncomeStatement: { folderName: 'Financial Data' },
  ordinaryCashFlows: { folderName: 'Financial Data' },
  ordinaryEquityChanges: { folderName: 'Financial Data' },
  ordinaryFinancialAccounts: { folderName: 'Financial Data' },
  ordinaryFinancialConnections: { folderName: 'Financial Data' },
  ordinaryFinancialRatios: { folderName: 'Financial Data' },
  sales: { folderName: 'Financial Data' },
  additionalFinancialData: { folderName: 'Financial Data' },
  activityIncidents: { folderName: 'Incidents' },
  incidents: { folderName: 'Incidents' },
  asnefdata: { folderName: 'Incidents' },
  delinquencyFiles: { folderName: 'Incidents' },
  banks: { folderName: 'Company Data' },
  customers: { folderName: 'Company Data' },
  employees: { folderName: 'Company Data' },
  facilities: { folderName: 'Company Data' },
  providers: { folderName: 'Company Data' },
  riskControlElements: { folderName: 'Company Data' },
  trademarksEO: { folderName: 'Company Data' },
  deedsPublishedInBormeEO: { folderName: 'Trading Data' },
  corporateBodies: { folderName: 'Trading Data' },
  officialGazetteOfMercantileRegistryDetail: { folderName: 'Trading Data' },
  tradingInformation: { folderName: 'Trading Data' },
  iberPlusReportEO: { folderName: 'Product Reports' },
  investigatedReportEO: { folderName: 'Product Reports' },
  rankings: { folderName: 'Rankings' },
  evaluation: { folderName: 'Risk Analysis' },
  organisations: { folderName: 'Companies' },
  alerts: { folderName: 'Alerts' },
  alertTypes: { folderName: 'Alerts' },
  countries: { folderName: 'Tenders' },
  subscriptions: { folderName: 'Tenders' },
  cpvs: { folderName: 'Tenders' },
  tenders: { folderName: 'Tenders' },
  v2: { folderName: 'Tenders' },
  awardee: { folderName: 'Tenders' },
  awarder: { folderName: 'Tenders' },
  identifierType: { folderName: 'Tenders' }
}
